version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ci_web
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:9.2
    container_name: ci_postgres
    restart: always
    environment:
      POSTGRES_DB: ci_db
      POSTGRES_USER: ci_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: ci_adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  pgdata:
